before_install:
  - gem install bundler
  - bundle config https://some-fake-gem-server.com 123:456
language: ruby
branches:
  only: master
rvm: # keep in sync with gemspec
  - 2.3
  - 2.4
  - 2.5
  - 2.6
